### ISSUE TITLE
buttons and text in map need to be smaller

### ISSUE THREAD

**Issue by qaztiel** [qaztiel/tibiaguessr#37]
the buttons and text in tibia map are too large make them smaller

**Comment by Rishav1707** [comment]
![Screenshot 2022-12-12 173152](https://user-images.githubusercontent.com/97666287/207040202-8aeb607e-2f1a-480d-8197-244e8460f9fe.png)
Are you talking about this button.

**Comment by Rishav1707** [comment]
And which text in tibia map?? @qaztiel

**Comment by qaztiel** [comment]
![image](https://user-images.githubusercontent.com/19220186/207083532-f6e274e3-7845-4aa8-834c-a978ebb28905.png)
ya the buttons and text, lets see if we can make them percentage based or something, they just seem too big for the map at the current size

**Comment by Rishav1707** [comment]
Ok I'll work on this and report to you soon.
