### ISSUE TITLE
guess button needs some styling and positioning

### ISSUE THREAD

**Issue by qaztiel** [qaztiel/tibiaguessr#47]
we could make the button square or move the button around or change the background
I dont like the way its positioned, lets try to make it look a bit better

![Image](https://user-images.githubusercontent.com/19220186/207397128-cadd99cc-d2cf-421f-8c90-0f429af73c73.png)

**Comment by maddy020** [comment]
I would like to work over the issue
Please assign it to me

**Comment by maddy020** [comment]
Some changes has been done 
Please review and tell if any other change needed
![button](https://user-images.githubusercontent.com/103564105/209436204-7b207a3c-916a-487a-9762-f7d1f4c1c5bf.PNG)
