### ISSUE TITLE
update favicon with new logo

### ISSUE THREAD

**Issue by qaztiel** [qaztiel/tibiaguessr#48]

**Comment by maddy020** [comment]
Please give me a detailed ove this issue

**Comment by qaztiel** [comment]
add this to the public/images dir, and replace the address in index.html
![PROJECT_BENDER_CHAR](https://user-images.githubusercontent.com/19220186/207632142-f2b2445f-06af-4a93-832e-a1b2c06040a3.png)

![image](https://user-images.githubusercontent.com/19220186/207632340-2a521622-49af-4455-aed1-8f47e3d22fa6.png)
