### ISSUE TITLE
add DISCORD icon to the footer

### ISSUE THREAD

**Issue by qaztiel** [qaztiel/tibiaguessr#52]
get a icon for DISCORD and add to the footer, the link to the discord is
https://discord.gg/FuEKaqNZTf

**Comment by Rishav1707** [comment]
From where do I get the icon of GitHub?? @qaztiel

**Comment by qaztiel** [comment]
https://www.flaticon.com/free-icon/github_2111432?term=github&page=1&position=4&page=1&position=4&related_id=2111432&origin=search
@Rishav1707

**Comment by Rishav1707** [comment]
@qaztiel  How can I add the GitHub icon in the footer as it is already been imported from react bootstrap icons. 

![github](https://user-images.githubusercontent.com/97666287/208290078-ab2edb97-a65a-465b-8ae6-fa087fb192bd.png)

**Comment by qaztiel** [comment]
sorry i meant discord icon dude
use the react bootstrap icons and use the DISCORD icon @Rishav1707

**Comment by qaztiel** [comment]
https://icons.getbootstrap.com/
